const mongoose=require("mongoose")
const restaurantSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    deliveryTime:{
        type:Number,
        required:true
    },
    creater:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"UserForFoodDeliveryApp",
        required:true
    },
    menu:{
    type:[
        {
            name:{
                type:String,
                required:true
            },
            price:{
                type:Number,
                required:true 
            },
            quantity:{
                type:Number,
                default:0
            }
        }
    ],
    default:[]
    },
    offers:{
        type:[{
            offerId:{
                type:mongoose.Schema.Types.ObjectId,
                    ref:"OfferForFoodDelevery"
            }
        }],
        default:[]
    },
    reviews:{
        type:[
            {
                userId:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"UserForFoodDeliveryApp",
                    required:true 
                },
                reviewText:{
                    type:String,
                    required:true 
                },
                rating:{
                    type:Number,
                    max:5,
                    min:0,
                    default:0
                }
            }
        ],
        default:[]
    },
    tags:{
        type:[String],
        enum:["Thai","Indian","Chinise","Italian","Maxican","South indian"]
    }
},{timestamps:true})
const Restaurant2=new mongoose.model("Restaurant2",restaurantSchema)
module.exports=Restaurant2